### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by nohwnd** [pwilver12/canvas-vscode#2]
Please include screenshots in your github readme and vscode market place. It helps people to decide if they like the theme without installing it. Thanks :)

**Comment by pwilver12** [comment]
Thanks for the feedback @nohwnd ! That is next on the docket :)

**Comment by nohwnd** [comment]
Okay, you are now in the recently added list, so your plugin is easily discoverable right now. That is how I found it. You will not be in that list forever, so I'd add the screenshots rather sooner than later.

**Comment by pwilver12** [comment]
Screenshots added.
